name: Test pull request1
on:
  push:
    branches:
      - 'test/**'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test code
        run: echo 'Done'
